name: LambdaCreation
on: 
  push:
    branches: [hello_world_lambda]

jobs:
  cloudformation_lambda:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout from branch
        uses: actions/checkout@v4
      
      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ${{ variables.AWS_REGION }}

      # Deploy to AWS CloudFormation
      - name: Deploy Lambda AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v4
        with:
          name: hello-world-lambda-stack
          template: helloWorld.yaml
          no-fail-on-empty-changeset: "1"