name: Deploy

on:
  push:
    paths:
    branches: [lambda_api_data_extractor]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get on branch dir
        uses: actions/checkout@v4

      - name: Show working dir
        run: ls -l

      - name: Adding permission to sh
        run: chmod +x deploy.sh
      
      - name: Show working dir
        run: ls -l


      - name: Creating S3 bucket
        run: ./deploy.sh create-bucket
        shell: bash

      - name: Creating Lambda func
        run: ./deploy.sh create-lambda
        shell: bash


      - name: Updating Lambda code
        run: ./deploy.sh deploy-lambda-code
        shell: bash


  