name: Deploy

on:
  push:
    paths:
      - "./deploy.sh"
    branches: [lambda_api_data_extractor]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get on branch dir
        uses: actions/checkout@v4

      - name: Show working dir
        run: ls -a

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: "us-east-1"
  